# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.bridgeit.com:
  peer0.importer.bridgeit.com:
  peer0.exporter.bridgeit.com:
  peer0.importerbank.bridgeit.com:
  peer0.insurance.bridgeit.com:
  peer0.custom.bridgeit.com:

networks:
  trade:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-importer
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.importer.bridgeit.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f74d54518ef4a07250a8a625aea9da2f0136a5a8dad05abf3e013b09de93da8b_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.importer.bridgeit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f74d54518ef4a07250a8a625aea9da2f0136a5a8dad05abf3e013b09de93da8b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/importer.bridgeit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerImporter
    networks:
      - trade

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-exporter
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.exporter.bridgeit.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d3538fff173659e377be0bd2ca0bab67395733c98dc5b5fb837983c65f04add1_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.exporter.bridgeit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d3538fff173659e377be0bd2ca0bab67395733c98dc5b5fb837983c65f04add1_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/exporter.bridgeit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerExporter
    networks:
      - trade

  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-importerbank
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.importerbank.bridgeit.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f74d54518ef4a07250a8a625aea9da2f0136a5a8dad05abf3e013b09de93da8b_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.importerbank.bridgeit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f74d54518ef4a07250a8a625aea9da2f0136a5a8dad05abf3e013b09de93da8b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/importerbank.bridgeit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerImporterbank
    networks:
      - trade

  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurance
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurance.bridgeit.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f74d54518ef4a07250a8a625aea9da2f0136a5a8dad05abf3e013b09de93da8b_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.insurance.bridgeit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f74d54518ef4a07250a8a625aea9da2f0136a5a8dad05abf3e013b09de93da8b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/insurance.bridgeit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerinsurance
    networks:
      - trade

  ca4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-custom
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.custom.bridgeit.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f74d54518ef4a07250a8a625aea9da2f0136a5a8dad05abf3e013b09de93da8b_sk
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.custom.bridgeit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f74d54518ef4a07250a8a625aea9da2f0136a5a8dad05abf3e013b09de93da8b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/custom.bridgeit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCustom
    networks:
      - trade

  orderer.bridgeit.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bridgeit.com
    container_name: orderer.bridgeit.com
    networks:
      - trade

  peer0.importer.bridgeit.com:
    container_name: peer0.importer.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importer.bridgeit.com
    networks:
      - trade

  peer0.exporter.bridgeit.com:
    container_name: peer0.exporter.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.exporter.bridgeit.com
    networks:
      - trade

  peer0.importerbank.bridgeit.com:
    container_name: peer0.importerbank.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importerbank.bridgeit.com
    networks:
      - trade

  peer0.insurance.bridgeit.com:
    container_name: peer0.insurance.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.insurance.bridgeit.com
    networks:
      - trade

  peer0.custom.bridgeit.com:
    container_name: peer0.custom.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.custom.bridgeit.com
    networks:
      - trade
