NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.exporterbank.bridgeit.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.exporterbank.bridgeit.com-cert.pem
    OrganizationalUnitIdentifier: peer
